spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}