version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: ecommerce-app
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: mysuperlongsecretkeyforjwt1234567890
      JWT_EXPIRATION: 3600000
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  postgres-data: