version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: mysuperlongsecretkeyforjwt1234567890
      JWT_EXPIRATION: 3600000
    ports:
      - "8080:8080"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:

volumes:
  postgres-data: