//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.03 at 02:17:26 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/ecommerce/orders", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.ecommerce.soap;
